---
stages:
  build_wf_yolo_dataset:
    cmd: >-
      uv run python scripts/build_wf_yolo_dataset.py
      --registry data/raw/wildfire/registry.json
      --data-dir data/raw/wildfire/data
      --output data/processed/wildfire_yolo
      --max-per-seq 10
      --random-seed 0
    deps:
      - scripts/build_wf_yolo_dataset.py
      - data/raw/wildfire/registry.json
      - data/raw/wildfire/data
    outs:
      - data/processed/wildfire_yolo

  build_fp_yolo_dataset:
    cmd: >-
      uv run python scripts/build_fp_yolo_dataset.py
      --registry data/raw/fp/registry.json
      --data-dir data/raw/fp/data
      --wf-dataset data/processed/wildfire_yolo
      --output data/processed/fp_yolo
      --random-seed 0
    deps:
      - scripts/build_fp_yolo_dataset.py
      - data/raw/fp/registry.json
      - data/raw/fp/data
      - data/processed/wildfire_yolo
    outs:
      - data/processed/fp_yolo

  merge_yolo_dataset:
    cmd: >-
      uv run python scripts/merge_yolo_dataset.py
      --wf-dataset data/processed/wildfire_yolo
      --fp-dataset data/processed/fp_yolo
      --output-train-val data/processed/yolo_train_val
      --output-test data/processed/yolo_test
    deps:
      - scripts/merge_yolo_dataset.py
      - data/processed/wildfire_yolo
      - data/processed/fp_yolo
    outs:
      - data/processed/yolo_train_val
      - data/processed/yolo_test

  visualize_yolo_train_val:
    cmd: >-
      uv run python scripts/visualize_dataset.py
      --dir-dataset data/processed/yolo_train_val
      --dir-save data/reporting/viz/yolo_train_val
    deps:
      - scripts/visualize_dataset.py
      - data/processed/yolo_train_val
    outs:
      - data/reporting/viz/yolo_train_val

  visualize_yolo_test:
    cmd: >-
      uv run python scripts/visualize_dataset.py
      --dir-dataset data/processed/yolo_test
      --dir-save data/reporting/viz/yolo_test
    deps:
      - scripts/visualize_dataset.py
      - data/processed/yolo_test
    outs:
      - data/reporting/viz/yolo_test
